enum tipoItem{ ROTULO=1, DIRETIVA=2, INSTRUCAO=3, DECIMAL=4, HEXADECIMAL=5, ENTRE_ASPAS=6, DESCONHECIDO=7};
enum tipoDiretiva{ ORG=1, ALIGN=2, WORD=3, WFILL=4, SET=5};
enum tipoPalavra{ NUMERO_HEXA=1, INSTRUCOES=2};

#ifndef LADO
#define LADO
enum lado{ESQUERDA=1, DIREITA=2};
#endif
