enum tipoItem{ ROTULO=1, DIRETIVA=2, INSTRUCAO=3, DECIMAL=4, HEXADECIMAL=5};
enum tipoDiretiva{ ORG=1, ALIGN=2, WORD=3, WFILL=4, SET=5};
enum tipoPalavra{ NUMERO_HEXA=1, INSTRUCO_DIR=2, INTRUCAO_ESQ=3};